fn hot(int x) -> int {
    int y = x;
    for (int i = 0; i < 200; i = i + 1) {
        y = y + (10 * 20);
        y = y - (500 + 1);
        y = y + (3 * 7);
        y = y % 97;
    }
    return y;
}

fn main() {
    int warm = 0;
    for (int i = 0; i < 300; i = i + 1) {
        warm = warm + hot(i);
    }

    int sum = 0;
    for (int i = 0; i < 10000; i = i + 1) {
        sum = sum + hot(i);
    }

    println(sum + warm);
}
