fn hot(int x) -> int {
    int y = x;
    for (int i = 0; i < 200; i = i + 1) {
        y = y + (i * 3);
        y = y * 2 + 1;
        y = y - (y / 3);
    }
    return y;
}

fn main() -> int {
    int warm = 0;
    for (int i = 0; i < 200; i = i + 1) {
        warm = warm + hot(i);
    }

    int start = time();
    int sum = 0;
    for (int i = 0; i < 3000; i = i + 1) {
        sum = sum + hot(i);
    }
    int end = time();

    print("App time:");
    print(end - start);
    return sum;
}